// Command genranges regenerates internal/ipowner/ranges.txt from official,
// provider-published IP range feeds. It runs at development time only; the
// agentegress binary embeds the result and never fetches anything.
//
//	go run ./tools/genranges
package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/netip"
	"os"
	"slices"
	"strings"
	"time"
)

// Hand-verified allocations that no provider feed covers. Every entry must cite
// the RDAP record it was checked against.
var manual = []struct{ prefix, org, source string }{
	{"160.79.104.0/21", "Anthropic", "RDAP ARIN NET-160-79-104-0-1 (Anthropic, PBC), checked 2026-09-25"},
	{"2607:6bc0::/32", "Anthropic", "RDAP ARIN ANTHROPIC-V6 (Anthropic, PBC), checked 2026-09-25"},
}

type entry struct {
	p   netip.Prefix
	org string
}

func main() {
	var all []entry
	var sources []string
	add := func(org, src string, prefixes []string) {
		n := 0
		for _, s := range prefixes {
			p, err := netip.ParsePrefix(strings.TrimSpace(s))
			if err != nil {
				continue
			}
			all = append(all, entry{p.Masked(), org})
			n++
		}
		sources = append(sources, fmt.Sprintf("%s: %s (%d prefixes)", org, src, n))
	}

	for _, m := range manual {
		add(m.org, m.source, []string{m.prefix})
	}

	cf4 := lines(get("https://www.cloudflare.com/ips-v4"))
	cf6 := lines(get("https://www.cloudflare.com/ips-v6"))
	add("Cloudflare", "https://www.cloudflare.com/ips-v4 + ips-v6", append(cf4, cf6...))

	add("Google Cloud", "https://www.gstatic.com/ipranges/cloud.json", googPrefixes("https://www.gstatic.com/ipranges/cloud.json"))
	add("Google", "https://www.gstatic.com/ipranges/goog.json", googPrefixes("https://www.gstatic.com/ipranges/goog.json"))

	var aws struct {
		V4 []struct {
			P       string `json:"ip_prefix"`
			Service string `json:"service"`
		} `json:"prefixes"`
		V6 []struct {
			P       string `json:"ipv6_prefix"`
			Service string `json:"service"`
		} `json:"ipv6_prefixes"`
	}
	decode(get("https://ip-ranges.amazonaws.com/ip-ranges.json"), &aws)
	var a []string
	for _, p := range aws.V4 {
		if p.Service == "AMAZON" { // superset of every other service entry
			a = append(a, p.P)
		}
	}
	for _, p := range aws.V6 {
		if p.Service == "AMAZON" {
			a = append(a, p.P)
		}
	}
	add("Amazon AWS", "https://ip-ranges.amazonaws.com/ip-ranges.json (service AMAZON)", a)

	// GitHub: skip "actions", which is a copy of Azure ranges and would label
	// unrelated Azure traffic as GitHub.
	var gh map[string]json.RawMessage
	decode(get("https://api.github.com/meta"), &gh)
	var g []string
	for _, k := range []string{"web", "api", "git", "packages", "pages", "copilot"} {
		var list []string
		if raw, ok := gh[k]; ok && json.Unmarshal(raw, &list) == nil {
			g = append(g, list...)
		}
	}
	add("GitHub", "https://api.github.com/meta (web, api, git, packages, pages, copilot)", g)

	var fastly struct {
		V4 []string `json:"addresses"`
		V6 []string `json:"ipv6_addresses"`
	}
	decode(get("https://api.fastly.com/public-ip-list"), &fastly)
	add("Fastly", "https://api.fastly.com/public-ip-list", append(fastly.V4, fastly.V6...))

	var m365 []struct {
		IPs []string `json:"ips"`
	}
	decode(get("https://endpoints.office.com/endpoints/worldwide?clientrequestid=b10c5ed1-bad1-445f-b386-b919946339a7"), &m365)
	var ms []string
	for _, e := range m365 {
		ms = append(ms, e.IPs...)
	}
	add("Microsoft 365", "https://endpoints.office.com/endpoints/worldwide", ms)

	// A more specific prefix wins at lookup time, so duplicates across feeds are
	// fine; drop exact duplicates, keeping the first (most specific source) label.
	seen := map[netip.Prefix]bool{}
	var out []entry
	for _, e := range all {
		if !seen[e.p] {
			seen[e.p] = true
			out = append(out, e)
		}
	}
	slices.SortFunc(out, func(x, y entry) int {
		if c := x.p.Addr().Compare(y.p.Addr()); c != 0 {
			return c
		}
		return x.p.Bits() - y.p.Bits()
	})

	f, err := os.Create("internal/ipowner/ranges.txt")
	check(err)
	w := bufio.NewWriter(f)
	fmt.Fprintf(w, "# Generated by go run ./tools/genranges on %s. Do not edit.\n", time.Now().UTC().Format("2006-01-02"))
	for _, s := range sources {
		fmt.Fprintf(w, "# %s\n", s)
	}
	for _, e := range out {
		fmt.Fprintf(w, "%s %s\n", e.p, e.org)
	}
	check(w.Flush())
	check(f.Close())
	fmt.Printf("wrote %d prefixes\n", len(out))
	for _, s := range sources {
		fmt.Println(" ", s)
	}
}

// googPrefixes decodes into a fresh value each time: json.Unmarshal reuses slice
// elements, so a shared struct would leak ipv4Prefix values into ipv6 rows.
func googPrefixes(url string) []string {
	var goog struct {
		Prefixes []struct {
			V4 string `json:"ipv4Prefix"`
			V6 string `json:"ipv6Prefix"`
		} `json:"prefixes"`
	}
	decode(get(url), &goog)
	var out []string
	for _, p := range goog.Prefixes {
		out = append(out, p.V4+p.V6)
	}
	return out
}

func get(url string) []byte {
	c := &http.Client{Timeout: 30 * time.Second}
	resp, err := c.Get(url)
	check(err)
	defer resp.Body.Close()
	if resp.StatusCode != 200 {
		check(fmt.Errorf("%s: %s", url, resp.Status))
	}
	b, err := io.ReadAll(resp.Body)
	check(err)
	return b
}

func decode(b []byte, v any) { check(json.Unmarshal(b, v)) }

func lines(b []byte) []string { return strings.Fields(string(b)) }

func check(err error) {
	if err != nil {
		fmt.Fprintln(os.Stderr, "genranges:", err)
		os.Exit(1)
	}
}
